name: Tests

on:
  workflow_run:
    workflows: ["Code check"]
    types: 
      - completed

env:
  PROJECT_NAME: GITLAB-CI

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/app/dev-requirements.txt
        pip install pytest
    - name: Run tests with pytest
      run: |
        pytest backend/app/app
